package producer

const (
	EVENT_TYPE_UNKNOWN_EVENT                   = "UnknownEvent"
	EVENT_TYPE_START_EVENT_V3                  = "StartEventV3"
	EVENT_TYPE_QUERY_EVENT                     = "QueryEvent"
	EVENT_TYPE_STOP_EVENT                      = "StopEvent"
	EVENT_TYPE_ROTATE_EVENT                    = "RotateEvent"
	EVENT_TYPE_INTVAR_EVENT                    = "IntVarEvent"
	EVENT_TYPE_LOAD_EVENT                      = "LoadEvent"
	EVENT_TYPE_SLAVE_EVENT                     = "SlaveEvent"
	EVENT_TYPE_CREATE_FILE_EVENT               = "CreateFileEvent"
	EVENT_TYPE_APPEND_BLOCK_EVENT              = "AppendBlockEvent"
	EVENT_TYPE_EXEC_LOAD_EVENT                 = "ExecLoadEvent"
	EVENT_TYPE_DELETE_FILE_EVENT               = "DeleteFileEvent"
	EVENT_TYPE_NEW_LOAD_EVENT                  = "NewLoadEvent"
	EVENT_TYPE_RAND_EVENT                      = "RandEvent"
	EVENT_TYPE_USER_VAR_EVENT                  = "UserVarEvent"
	EVENT_TYPE_FORMAT_DESCRIPTION_EVENT        = "FormatDescriptionEvent"
	EVENT_TYPE_XID_EVENT                       = "XIDEvent"
	EVENT_TYPE_BEGIN_LOAD_QUERY_EVENT          = "BeginLoadQueryEvent"
	EVENT_TYPE_EXECUTE_LOAD_QUERY_EVENT        = "ExectueLoadQueryEvent"
	EVENT_TYPE_TABLE_MAP_EVENT                 = "TableMapEvent"
	EVENT_TYPE_WRITE_ROWS_EVENTv0              = "WriteRowsEventV0"
	EVENT_TYPE_UPDATE_ROWS_EVENTv0             = "UpdateRowsEventV0"
	EVENT_TYPE_DELETE_ROWS_EVENTv0             = "DeleteRowsEventV0"
	EVENT_TYPE_WRITE_ROWS_EVENTv1              = "WriteRowsEventV1"
	EVENT_TYPE_UPDATE_ROWS_EVENTv1             = "UpdateRowsEventV1"
	EVENT_TYPE_DELETE_ROWS_EVENTv1             = "DeleteRowsEventV1"
	EVENT_TYPE_INCIDENT_EVENT                  = "IncidentEvent"
	EVENT_TYPE_HEARTBEAT_EVENT                 = "HeartbeatEvent"
	EVENT_TYPE_IGNORABLE_EVENT                 = "IgnorableEvent"
	EVENT_TYPE_ROWS_QUERY_EVENT                = "RowsQueryEvent"
	EVENT_TYPE_WRITE_ROWS_EVENTv2              = "WriteRowsEventV2"
	EVENT_TYPE_UPDATE_ROWS_EVENTv2             = "UpdateRowsEventV2"
	EVENT_TYPE_DELETE_ROWS_EVENTv2             = "DeleteRowsEventV2"
	EVENT_TYPE_GTID_EVENT                      = "GTIDEvent"
	EVENT_TYPE_ANONYMOUS_GTID_EVENT            = "AnonymousGTIDEvent"
	EVENT_TYPE_PREVIOUS_GTIDS_EVENT            = "PreviousGTIDsEvent"
	EVENT_TYPE_MARIADB_ANNOTATE_ROWS_EVENT     = "MariadbAnnotateRowsEvent"
	EVENT_TYPE_MARIADB_BINLOG_CHECKPOINT_EVENT = "MariadbBinLogCheckPointEvent"
	EVENT_TYPE_MARIADB_GTID_EVENT              = "MariadbGTIDEvent"
	EVENT_TYPE_MARIADB_GTID_LIST_EVENT         = "MariadbGTIDListEvent"
)
